 
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.ButtonGroup;
import java.sql.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.Reader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.awt.event.MouseListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseAdapter;
import java.awt.geom.Point2D;
import java.awt.Point;
import java.awt.geom.*;
import java.awt.*;
import java.util.LinkedList;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JComboBox;
import javax.swing.JCheckBox;
import javax.swing.JScrollPane;

//import javax.swing.JScrollPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Challenge extends javax.swing.JFrame {

    /**
     * Creates new form Challengee
     */
    public Challenge() {
        initComponents();
            jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); 
jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); 
jScrollPane4.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
jScrollPane4.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        
      jTable1.addMouseListener(new MouseAdapter() {
  public void mouseClicked(MouseEvent e) {
 // System.out.println("Hai");
  JFrame frame1 = new JFrame();
  JPanel review = new JPanel(new BorderLayout());
  //JPanel review = new JPanel();
  //frame1.setSize(1000,1000);
        review.setPreferredSize(new Dimension(1500, 1500));
        review.setBackground(new java.awt.Color(153, 255, 153));
    javax.swing.JScrollPane jMyScrollPane;
    javax.swing.JTable jMyTable;
    
        jMyScrollPane = new javax.swing.JScrollPane();
        jMyTable = new javax.swing.JTable();
 
   
   jMyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null,null, null, null, null},
                {null,null, null, null, null},
                {null,null, null, null, null},
                {null,null, null, null, null}
            },
            new String [] {
                "Review Date", "Stars", "Review Text", "UserID"," Useful Votes"
            }
        )); 
    
    jMyTable.getColumnModel().getColumn(2).setPreferredWidth(800);
    //JComponent comp = new JPanel(new BorderLayout());
 //comp.add(pane);
    
    jMyScrollPane.setViewportView(jMyTable);
    JTable target = (JTable)e.getSource();
    DefaultTableModel model = (DefaultTableModel) target.getModel();
    int row = target.getSelectedRow();
      //int column = target.getSelectedColumn();
    String bname=(String) model.getValueAt(row,0);
    String businessname="";
    
    int n=bname.lastIndexOf("'");
    if(n!=-1)
    {
    for(int ne=0;ne<=n;ne++)
    {
    businessname+=bname.charAt(ne);
    }
    businessname+="'";
    for(int ha=n+1;ha<bname.length();ha++)
    {
    businessname+=bname.charAt(ha);
    
    }
    } 
    
    else
    {
    for(int ne1=0;ne1<bname.length();ne1++)
    {
    businessname+=bname.charAt(ne1);
    }
    }
    int rowCount = model.getRowCount();
    //System.out.println(businessname+" "+rowCount);
    //System.out.println(row);
    DefaultTableModel model1 = (DefaultTableModel) jMyTable.getModel();
    int rowCount1 = model1.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount1 - 1; i >= 0; i--) {
    model1.removeRow(i);
}  


Connection conn;
        String queryy="";
        ResultSet rset;

     
   try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
     Statement stmt = conn.createStatement();       

     //queryy="select distinct attribute from attributes where business_id in (select business_id from categories where category='"+jCheckBoxTemp1.getActionCommand()+"') ";
     
     queryy="select RevDate, Stars, text, ruser_id, ruseful from yelp_review where business_id in (select distinct business_id from yelp_business where bname='"+businessname+"')"; 
//querry=""     

     rset = stmt.executeQuery(queryy);
     
     while (rset.next()) {
          
        Clob clob = rset.getClob("text");
        //clob.getSubString(1, (int) clob.length()
model1.addRow(new Object[]{rset.getString("revdate"),rset.getInt("stars"),clob.getSubString(1, (int) clob.length()),rset.getString("ruser_id"),rset.getInt("ruseful")});   

}

}
catch(SQLException e1){e1.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
 
 
   
     
     

   
        
        review.add(jMyScrollPane,BorderLayout.CENTER);
        frame1.getContentPane().add(review);
        frame1.pack();
        frame1.setVisible(true);
    //if (e.getClickCount() == 2) {
      //JTable target = (JTable)e.getSource();
      //int row = target.getSelectedRow();
      //int column = target.getSelectedColumn();
      // do some action if appropriate column
    //}
        
    
  }
});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setForeground(new java.awt.Color(102, 204, 255));

        jCheckBox1.setText("Active Life");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Arts & Entertainment");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Automotive");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Car Rental");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Cafes");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Beauty & Spas");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox7.setText("Convenience Stores");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox8.setText("Dentists");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Doctors");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox10.setText("Drugstores");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox11.setText("Department Stores");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox12.setText("Education");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox13.setText("Event Planning & Services");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox14.setText("Flowers & Gifts");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox15.setText("Food");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox16.setText("Health & Medical");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox17.setText("Home Services");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox18.setText("Home & Garden");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox19.setText("Hospitals");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox20.setText("Hotels & Travel");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox21.setText("Hardware Stores");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox22.setText("Grocery");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox23.setText("Medical Centers");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox24.setText("Nurseries & Gardening");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox25.setText("Nightlife");
        jCheckBox25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox25ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox26.setText("Restaurants");
        jCheckBox26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox26ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox27.setText("Shopping");
        jCheckBox27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox27ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });

        jCheckBox28.setText("Transportation");
        jCheckBox28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox28ActionPerformed(evt);
                jCheckBoxAActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 123, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox28)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel4);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Day of the week");

        jLabel3.setText("From:");

        jLabel4.setText("To:");

        jLabel5.setText("Search For:");

        jPanel5.setBackground(new java.awt.Color(255, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(jPanel5);

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true), new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 1, true))));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Business", "City", "State", "Stars"
            }
        ));
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
        jScrollPane3.setViewportView(jTable1);

        jButton1.setText("Welcome to Yelp Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");

        jButton3.setText("Close");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                //.addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                //.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            //.addComponent(jComboBox2, 0, 59, Short.MAX_VALUE)
                            //.addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            //.addComponent(jComboBox3, 0, 71, Short.MAX_VALUE)
                            //.addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            )))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    //.addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    //.addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        //.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        //.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        )
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            //.addComponent(jLabel2)
                            //.addComponent(jLabel3)
                            //.addComponent(jLabel4)
                            //.addComponent(jLabel5)
                            )
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            //.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            //.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            //.addComponent(jComboBox3)
                            //.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            ))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        //.addComponent(jButton3)
                        //.addComponent(jButton2)
                        )))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

                                             

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
      
    }
    
    
       private void jAActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        //jScrollPane4.setViewportView(jPanel5);
Connection conn;
        String queryy="";
        ResultSet rset;

 //Object temp=evt.getSource();
 //javax.swing.JCheckBox jCheckBoxTemp=(JCheckBox) temp; 
 Object objects,objects2;
  DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    dm.removeRow(i);
}
  
   javax.swing.JCheckBox jCheckBoxTemp1;
    jScrollPane4.setViewportView(jPanel5);
jScrollPane1.setViewportView(jPanel2);
jScrollPane2.setViewportView(jPanel4);

   
   for(Component component : jPanel5.getComponents()) {
   
   objects=component;
   jCheckBoxTemp1=(JCheckBox) objects;
   
        if(jCheckBoxTemp1.isSelected())
        {
   
        temporary++;
            try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
     Statement stmt = conn.createStatement();       

     //queryy="select distinct attribute from attributes where business_id in (select business_id from categories where category='"+jCheckBoxTemp1.getActionCommand()+"') ";
     
     queryy="select distinct bname, city, state, stars from yelp_business where business_id in (select business_id from attributes where attribute='"+jCheckBoxTemp1.getActionCommand()+"')"; 
     
     rset = stmt.executeQuery(queryy);
     while (rset.next()) {
     
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                int i=0;

 int nRow = model.getRowCount();
        for(int traverse = 0 ; traverse < nRow ; traverse++) {

   if(model.getValueAt(traverse,0).equals(rset.getString("bname")))
   i=1;
        }
    if(i==0)
model.addRow(new Object[]{rset.getString("bname"),rset.getString("city"),rset.getString("state"),rset.getInt("stars")});   

}

}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
 
             }
             }
                          
}
                                            

    private void jCheckBoxAActionPerformed(java.awt.event.ActionEvent evt) {                                           
        
        jScrollPane4.setViewportView(jPanel5);
Connection conn;
        String queryy="";
        ResultSet rset;

 Object temp=evt.getSource();
 javax.swing.JCheckBox jCheckBoxTemp=(JCheckBox) temp; 
 Object objects,objects2;
 
 for(Component component : jPanel5.getComponents()) {
 objects=component;
 jPanel5.remove((JCheckBox) objects);
}

DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
int rowCount = dm.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    dm.removeRow(i);
}
 
   javax.swing.JCheckBox jCheckBoxTemp1;
    jScrollPane4.setViewportView(jPanel5);
jScrollPane1.setViewportView(jPanel2);
jScrollPane2.setViewportView(jPanel4);

   
   for(Component component : jPanel4.getComponents()) {
   
   objects=component;
   jCheckBoxTemp1=(JCheckBox) objects;
   
        if(jCheckBoxTemp1.isSelected())
        {
   
        temporary++;
            try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
     Statement stmt = conn.createStatement();       

     queryy="select distinct attribute from attributes where business_id in (select business_id from categories where category='"+jCheckBoxTemp1.getActionCommand()+"') ";
     rset = stmt.executeQuery(queryy);
     while (rset.next()) {
     jPanel5.setLayout(new BoxLayout(jPanel5, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("attribute"));
                int i=0;
Object objects1;
 javax.swing.JCheckBox jCheckBoxTemp2;
        for(Component component1 : jPanel5.getComponents()) {
        objects1=component1;
   jCheckBoxTemp2=(JCheckBox) objects1;
   if(jCheckBoxTemp2.getActionCommand().equals(rset.getString("attribute")))
   i=1;
        }
    if(i==0)
   {
   jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox29);
 }          
}

}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
 
             }
             }
                          
}

                                 

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) { 
                                              
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox1.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Restaurants') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
     jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[0][countCheckBoxes[0]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[0]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[0];g++){
            jPanel4.remove((JCheckBox) obj1[0][g]);
            }
    	countCheckBoxes[0]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox2.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");

     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Arts & Entertainment') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[1][countCheckBoxes[1]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[1]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[1];g++){
            jPanel4.remove((JCheckBox) obj1[1][g]);
            }
    	countCheckBoxes[1]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox3.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Automotive') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[2][countCheckBoxes[2]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[2]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[2];g++){
            jPanel4.remove((JCheckBox) obj1[2][g]);
            }
    	countCheckBoxes[2]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox4.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Car Rental') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[3][countCheckBoxes[3]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[3]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[3];g++){
            jPanel4.remove((JCheckBox) obj1[3][g]);
            }
    	countCheckBoxes[3]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox5.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Cafes') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[4][countCheckBoxes[4]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[4]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[4];g++){
            jPanel4.remove((JCheckBox) obj1[4][g]);
            }
    	countCheckBoxes[4]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox6.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Beauty & Spas') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[5][countCheckBoxes[5]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[5]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
 }
    else
    {
    	for(int g=0;g<countCheckBoxes[5];g++){
            jPanel4.remove((JCheckBox) obj1[5][g]);
            }
    	countCheckBoxes[5]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox7.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Convenience Stores') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[6][countCheckBoxes[6]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[6]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[6];g++){
            jPanel4.remove((JCheckBox) obj1[6][g]);
            }
    	countCheckBoxes[6]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox8.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Dentists') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[7][countCheckBoxes[7]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[7]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[7];g++){
            jPanel4.remove((JCheckBox) obj1[7][g]);
            }
    	countCheckBoxes[7]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox9.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Doctors') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[8][countCheckBoxes[8]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[8]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[8];g++){
            jPanel4.remove((JCheckBox) obj1[8][g]);
            }
    	countCheckBoxes[8]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox10.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Drugstores') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[9][countCheckBoxes[9]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[9]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[9];g++){
            jPanel4.remove((JCheckBox) obj1[9][g]);
            }
    	countCheckBoxes[9]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox11.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Department Stores') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[10][countCheckBoxes[10]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[10]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[10];g++){
            jPanel4.remove((JCheckBox) obj1[10][g]);
            }
    	countCheckBoxes[10]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox12.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Education') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[11][countCheckBoxes[11]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[11]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[11];g++){
            jPanel4.remove((JCheckBox) obj1[11][g]);
            }
    	countCheckBoxes[11]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox13.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
  
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Event Planning & Services') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[12][countCheckBoxes[12]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[12]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[12];g++){
            jPanel4.remove((JCheckBox) obj1[12][g]);
            }
    	countCheckBoxes[12]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	
    if(jCheckBox14.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
  
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Flowers & Gifts') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[13][countCheckBoxes[13]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[13]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[13];g++){
            jPanel4.remove((JCheckBox) obj1[13][g]);
            }
    	countCheckBoxes[13]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox15.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Food') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[14][countCheckBoxes[14]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[14]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[14];g++){
            jPanel4.remove((JCheckBox) obj1[14][g]);
            }
    	countCheckBoxes[14]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox16.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
  
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Health & Medical') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[15][countCheckBoxes[15]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[15]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[15];g++){
            jPanel4.remove((JCheckBox) obj1[15][g]);
            }
    	countCheckBoxes[15]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	
    if(jCheckBox17.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Home Services') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[16][countCheckBoxes[16]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[16]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[16];g++){
            jPanel4.remove((JCheckBox) obj1[16][g]);
            }
    	countCheckBoxes[16]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox18.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
  
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Home & Garden') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[17][countCheckBoxes[17]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[17]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[17];g++){
            jPanel4.remove((JCheckBox) obj1[17][g]);
            }
    	countCheckBoxes[17]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox19.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Hospitals') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[18][countCheckBoxes[18]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[18]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[18];g++){
            jPanel4.remove((JCheckBox) obj1[18][g]);
            }
    	countCheckBoxes[18]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox20.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
  
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Hotels & Travel') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[19][countCheckBoxes[19]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[19]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[19];g++){
            jPanel4.remove((JCheckBox) obj1[19][g]);
            }
    	countCheckBoxes[19]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	jScrollPane2.setViewportView(jPanel4);
    if(jCheckBox21.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Hardware Stores') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[20][countCheckBoxes[20]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[20]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[20];g++){
            jPanel4.remove((JCheckBox) obj1[20][g]);
            }
    	countCheckBoxes[20]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox22.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Grocery') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[21][countCheckBoxes[21]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[21]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[21];g++){
            jPanel4.remove((JCheckBox) obj1[21][g]);
            }
    	countCheckBoxes[21]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox23.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Medical Centers') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
  obj1[22][countCheckBoxes[22]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[22]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[22];g++){
            jPanel4.remove((JCheckBox) obj1[22][g]);
            }
    	countCheckBoxes[22]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox24.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
  
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Nurseries & Gardening') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[23][countCheckBoxes[23]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[23]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[23];g++){
            jPanel4.remove((JCheckBox) obj1[23][g]);
            }
    	countCheckBoxes[23]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox25ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox25.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Nightlife') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[24][countCheckBoxes[24]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[24]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[24];g++){
            jPanel4.remove((JCheckBox) obj1[24][g]);
            }
    	countCheckBoxes[24]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox26ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    jScrollPane2.setViewportView(jPanel4);	 
    if(jCheckBox26.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Restaurants') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[25][countCheckBoxes[25]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[25]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[25];g++){
            jPanel4.remove((JCheckBox) obj1[25][g]);
            }
    	countCheckBoxes[25]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox27ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	
    if(jCheckBox27.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Shopping') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[26][countCheckBoxes[26]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[26]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
           
        
        //jPanel4.add(cb4);
        //jPanel4.add(cb5);
        
        
       
    }
    else
    {
    	for(int g=0;g<countCheckBoxes[26];g++){
            jPanel4.remove((JCheckBox) obj1[26][g]);
            }
    	countCheckBoxes[26]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

private void jCheckBox28ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	 
    if(jCheckBox28.isSelected())	
    {
    try{
Connection conn;
        
conn = DriverManager.getConnection("jdbc:mysql://localhost/yelp","yelp","mypassword");
 
     Statement stmt = conn.createStatement();
     String queryy="select distinct category from categories where business_id in (select business_id from categories where category='Transportation') ";
     ResultSet rset = stmt.executeQuery(queryy);
     while (rset.next()) {
 jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
      jCheckBox29 = new javax.swing.JCheckBox();
       jCheckBox29.setAlignmentX(Component.LEFT_ALIGNMENT);
        jCheckBox29.setText(rset.getString("category"));
        
        jCheckBox29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAActionPerformed(evt);
            }
        });
        
        
  obj1[27][countCheckBoxes[27]]=jCheckBox29; 
        jPanel4.add(jCheckBox29);
         countCheckBoxes[27]++;
          
}
}
catch(SQLException e){e.printStackTrace();System.out.println("SQL Exception (Database Problem)");}
        
       
    }
    
    else
    {
    	for(int g=0;g<countCheckBoxes[27];g++){
            jPanel4.remove((JCheckBox) obj1[27][g]);
            }
    	countCheckBoxes[27]=0;
    	
    
    }
        //System.out.println(countCheckBoxes);
    }                                          

                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Challenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Challenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Challenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Challenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Challenge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    
    // End of variables declaration                   
private javax.swing.JCheckBox jCheckBox29;
private javax.swing.JCheckBox jCheckBox30;
int[] countCheckBoxes=new int[1000];
Object[][] obj1=new Object[50][1000];
int temporary=0;


}
